### PR TITLE
hide header on macOS, thanks to @henrikdahl, fix #1

### LINKED ISSUE #1: Doesn't seem to work well on OSX
screen shot 2016-12-16 at 14 51 21

OSX 10.12.1

### PR DESCRIPTION
**Pull request by jancborchardt**
Based on the comment by @henrikdahl at https://github.com/jancborchardt/hyperminimal/issues/1#issuecomment-267751125 – thank you! :tada: 

But since I don’t have macOS myself I can’t test and I’m not sure which additional styles are needed. Please test and let me know how it looks @hedefalk. (And maybe @eppfel @xMartin do you use Hyper? ;)

### CODE REVIEW

**Comment by hedefalk** [comment]
Sorry, I'm pretty new to hyper, don't even know how to try from source. Wanna help though! Only found this:

```
  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
```

Could I then check out your macos-header branch and then simply `ln -s` it into `~/.hyper_plugins/local/` ?

**Comment by jancborchardt** [comment]
@hedefalk yes, that should work! :) I’m also only using Hyper from the package and am pretty new to it.

@rmurai0610 so you can confirm this works? :)

**Comment by rmurai0610** [comment]
Yes, it should work if you make symbolic link to ~/.hyper_plugins/local and include the directory name inside the localPlugin
ie. In this case 
`  localPlugins: [
    'hyperminimal'
  ]
`

**Comment by hedefalk** [comment]
Master looks like 

screen shot 2016-12-21 at 22 14 00

for me now. The outstanding PR, is that maybe a fix? Just needs a whitespace cleanup?

**Comment by henrikruscon** [comment]
@hedefalk PR that got merged is pretty much redundant. Not sure why @jancborchardt decided to merge that one instead of mine.

Current master **with** tabs _(still shows area where traffic buttons resides & broken margin/padding)_
skarmavbild 2016-12-21 kl 23 54 19

 #4 PR master **with** tabs
skarmavbild 2016-12-21 kl 23 59 22

Current master **without** tabs _(title still visible)_
skarmavbild 2016-12-22 kl 00 01 33

 #4 PR master **without** tabs
skarmavbild 2016-12-22 kl 00 01 18


Also, hiding the `header_header` like the merged PR does is generally a bad idea and not the proper approach. I hide `tabs_title` instead.

**Comment by jancborchardt** [comment]
Also here for info @henrikdahl – sorry about the mess-up, I saw your pull request only after the other ones. :)

I tested your pull request and since the defaultCSS didn’t work on my Ubuntu but the windowsCSS does, I cherry-picked your commits and switched it around: https://github.com/jancborchardt/hyperminimal/pull/5

**Pull request merged**
