### PR TITLE
platform check, css for macos – rebased & works on Linux

### PR DESCRIPTION
**Pull request by jancborchardt**
@henrikdahl I rebased your pull request #4 on master here. And the defaultCSS didn’t work on my Ubuntu, but the windowsCSS does. So I changed the platform.check to darwin hence and used the windowsCSS as defaultCSS. :)

@henrikdahl @hedefalk @rmurai0610 should work for you still too, can you test?

### CODE REVIEW

**Comment by rmurai0610** [comment]
@jancborchardt @henrikdahl Sorry about the tab title hiding, I didn't notice the tabs_title.
However, the master branch looks like this on my laptop so I'm not too sure why it didn't work on others.
screen shot 2016-12-22 at 08 10 17

Anyways the latest changes looks like this with no tabs
screen shot 2016-12-22 at 08 15 29
With tabs
screen shot 2016-12-22 at 08 21 38

It seems to be working as intending I think.
However, I noticed that the spacing for the tabs is always there, meaning that the first 2 line of terminal is wasted if you don't have any tabs open.
Would it be possible to fix this by checking for number of tabs opens?

**Comment by jancborchardt** [comment]
@rmurai0610 it definitely shouldn’t look like that with the blank space above the input without tabs, that’s the entire point of this extension. :) 
Could you maybe test if taking parts of the defaultCSS makes it work as intended & shown in [the readme](https://github.com/jancborchardt/hyperminimal#hyperminimal)?

**Comment by rmurai0610** [comment]
If you include the 
`    .terms_terms {
      margin-top: 0;
    }
`
It works as intended until you open new tab
screen shot 2016-12-22 at 16 37 52
So it seems like we need to add the above code when there is 1 tab and remove it when we have multiple tabs

**Comment by jancborchardt** [comment]
Btw @henrikdahl @rmurai0610 I just invited you as collaborators to the repository so we can directly work together on branches like this. :)

**Comment by jancborchardt** [comment]
Soo @rmurai0610 @henrikdahl @hedefalk does this now work properly on macOS? :)

**Comment by jancborchardt** [comment]
@rmurai0610 @henrikdahl @hedefalk assuming this works for you now, I published the new version 0.0.6 to npm now so it’s fixed for macOS people. Let me know if there are still issues, and thanks a lot for your contributions! :)

**Comment by jancborchardt** [comment]
Btw @rmurai0610 do you have an account at npmjs.com? Then I can add you to the collaborator list at https://www.npmjs.com/package/hyperminimal too :)

**Comment by rmurai0610** [comment]
@jancborchardt 
https://www.npmjs.com/~rmurai0610
Just made an account :)

Also I noticed that some themes forces header to be added in causing first few line to be hidden behind it (At least on OS X)
(For example hyper-ayu)
screen shot 2016-12-27 at 12 19 16

**Comment by jancborchardt** [comment]
@rmurai0610 so in that case maybe we should work with a stronger rule or even `!important`? Maybe best open a new issue and let’s see there? :)

**Pull request merged**
