### PR TITLE
Remove titlebar covering top of part. Fixes #20

### LINKED ISSUE #20: Titlebar still occupies space after hiding
After hiding the title bar, there's still empty space at the top. Which is useful because you can still grab the window to move around, but it covers any text below it, which means you cannot select the text or do things such as alt+click.

Here is a screenshot which demonstrates the issue:

screenshot 2018-07-20 at 1 32 14 pm

For now, I added the following CSS in my config to remove the extra space so that it doesn't cover any text, but still allows me to move the window around (14px is my top padding):

```css
.tabs_nav {
  height: auto;
  min-height: 14px;
}
```

But it would be nice if this was done automatically.

### PR DESCRIPTION
**Pull request by satya164**
I added the CSS only for Mac OS because I'm using OS X and have no way of testing it on other OS currently.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Could the macOS folks review it? (I’m only on Ubuntu) cc @henrikdahl @gavanitrate @rmurai0610 @net not sure who of you has macOS. :)

**Comment by jbbudzon** [comment]
This works for me on OSX 10.13 😉

**Comment by jancborchardt** [comment]
@jbbudzon thanks a lot for the review! And thanks a lot @satya164 for the contribution! :)

**Comment by jancborchardt** [comment]
Fix is pushed to npm as v0.1.0 – thanks a lot for everyone’s help! :slightly_smiling_face:

**Pull request merged**
